# Generated by Django 3.2.25 on 2025-03-24 17:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrayscaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='grayscale_images/')),
                ('signature', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResizedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resized_images/')),
                ('grayscale_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.grayscaleimage')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attentioned_images/')),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attentioned_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.grayscaleimage')),
            ],
        ),
    ]
