# Generated by Django 3.2.25 on 2025-03-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_attentioned_image_attentionedimage_grayscale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionedimage',
            name='predicted_class',
            field=models.TextField(default='I don’t know'),
        ),
    ]
