# Generated by Django 5.2 on 2025-04-29 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_attentionedimage_predicted_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resizedimage",
            name="grayscale_image",
        ),
        migrations.DeleteModel(
            name="AttentionedImage",
        ),
        migrations.DeleteModel(
            name="ResizedImage",
        ),
    ]
